In [155]:
from matplotlib import pyplot as plt
import seaborn
import json
import socket
import numpy as np
import math

In [156]:
def recv_data(sock):
    if type(sock) == socket.socket:
        reader = sock.recv
        buff = 1000000
    else:
        reader = sock.read
        buff = 100000
    l = reader(4)
    l = byte_count(l)
    res = []
    cnt = 0
    while cnt < l:
        tmp = list(reader(buff if l - cnt > buff else l - cnt))
        cnt += len(tmp)
        res.extend(tmp)
    res = bytes(res)
    if not res:
        return None
    return json.loads(res)



In [157]:
FILE_NAME = '/home/max/Загрузки/besthack19/task1'

In [158]:
conn = open(FILE_NAME, 'rb')

In [159]:
msg_map = recv_data(conn)
sense = []
while True:
    tmp = recv_data(conn)
    if not tmp:
        break
    sense.append(tmp['data'] if 'data' in tmp else tmp)
print(len(sense))

1705


In [202]:
landMap = np.random.randint(0, 2, (3, 9))
landMap

array([[1, 0, 0, 1, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1]])

In [169]:
newHeight = np.full(9, 50)
newHeight

array([[0.],
       [0.]])

In [162]:
height = np.vstack([landMap[:1] - newHeight, landMap[1:]])
height

array([[ 10, -45,  27, -37, -18,  -8,  22, -49,  33],
       [ 87,  81,   7,  13,  22,  27,  91,  68,  42],
       [ 28,  41,  14,  15,  88,  16,  41,  45,  88]])

In [215]:
def find_sollution(landMap, heights, currentData):
    if (heights == None):
        #print(landMap[:1] - np.full(landMap[0].size, currentData['height']))
        heights = np.vstack([abs(landMap[:1] - np.full(landMap[0].size, currentData['height'])), landMap[1:]])
    else:
        heights -= np.vstack([np.full(heights[0].size, currentData['height']), np.zeros(2, heights[0].size)])
    heigths = heights.T[heights[0].argsort()].T[:5]
    res = (heights[1][0], heights[2][0])
    
    heights[1:2] += int(currentData['speed'] * math.cos(currentData['psi']))
    heights[2:] += int(currentData['speed'] * math.sin(currentData['psi']))
    edge = int(math.sqrt(landMap[0][1]))
    for i in range(len(heights[0])):
        heights[0][i] = landMap[0][heights[1][i] + heights[2][i] * edge]
    return (res, heights)
    

In [216]:
currentData = {"height":14, "speed":1, "psi":90}

In [217]:
find_sollution(landMap, None, currentData)

((0, 1), array([[1, 1, 1, 1, 1, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 1, 1],
        [1, 1, 1, 1, 0, 1, 1, 1, 1]]))